#!/bin/bash

# BOSH boxes do not have SWAP
# Default the swap check to OK the check operator has specifically asked for another status.

# We will default to OK rather than CRITICAL on BOSH boxes.
#  -n, --no-swap=<ok|warning|critical|unknown>
#    Resulting state when there is no swap regardless of thresholds. Default: CRITICAL
no_swap_option="--no-swap=ok"

if [[ $@ == *-n* ]];
then
   no_swap_option=""
fi

/var/vcap/packages/nagios-monitoring-plugins/libexec/check_swap_impl ${@} ${no_swap_option}